# Generated by Django 3.1.1 on 2020-12-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_task_sag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sag',
        ),
    ]
